language: node_js
node_js:
  - "4.3.1"

env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

deploy:
 provider: heroku
 api-key: HEROKU_API
 app: book-swap-meet
