language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  api_key:
    secure: TRPZagSuPBXqxqJUMXC1o12o+ByKOucBOLH8XoWuBWCrt+vQ2wGj5goDJ3EDWLUcNGni88O4yZnj/I1CZgic/NE2HKiHxZeJP1WOyGi4aCaB91z0AO4P1orB73od1yWripejGfAcMXJYT73ZJPy/q+QXCgfJb5agU7nEwDoPeJJZmhDZVGfW84UemagpCYQ2OQbnurM9idJWrm1kNPQTK0TrN7JDZkILTcwVf1120C4+zqB5H91bru90csZW2GywozKIDhFnByxYwKNTQqbiS9E/uaIeuT7Kyd4McGXlnvFoLyrO2POc0Q5X+slP+MzzvQ66eE9zRcbzZowjINRA3pro8KL5uYNLC5MRxGKBhDqn2LZ19sNt0wMRuLRt76d1GNDItYC/9iB9CSAdQaYM3fCKY2KNNSyM8Eyo0AGyn4rc3I3/ugLFldhWfYCro/D3k0go0gVPJkIiASWILroMiXnx/NMFY+on7tW1pxIsFvD0cg14KYvxZQY3rpKrseVbN1HNl1UlcGz1uUDORTKIqAcFWrQJ0v1zu/3TmGG8z8GGaxiPXbWUFp1nCEtOnCBm0bhV3X2xzn4TGLR8mFk+NhSyutn1SxWdu8Ln4O8qQOsxunQXhG/xclBLLRcP3Sm8rbMFRINb4Ejv5dqRRNLb0nZhJ4mcNeSsBL5pjsRAHcc=
  app: book-swap-meet
