language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  app: book-swap-meet
  api_key:
    secure: okvS1d4FogbfWzHuIKYdNUTxddbMPw5JzdYv6ojaOFkBv0e6mARoZoMe9SgxQ+ViiP7ovLiHNwd7whFCzj6Zi6ElQ4009X9iWYCF6fiYwxiQ3hwAvRhL8rP+94QcutPA03Gj0Q5vyRjotVOg7ayJa59gSxkgyY2vsZ5u1vICkBxzHnqXVaFAZvOXSEjM2P1j7eaTs7xuKG9NP7A6uhQXj0idm6fwbjGUGnGRwM72WcEnH2uCmw2IahrLKc75D2Kb8C47Z994D+JIcxnCxoaacB02Q3YuxyyPZpUN1pqoRFeXqqASR8sKTMv98Iv1wiA69T/DmgA6U5C1ntg9nMGAMy/fLut8t43/8ldsBv78USy4lRB+QlTcRWSo2syh2CUG6TaACtRj3m+aE9GnpO1qF7Ar4oXSymMbJF+ka1pGdyBZRqyB2v4iiZTYJeExgsxwvPafH34eMEfyaQ9+SgKLGMDYPABOSZUsZUxdWgMHSTc5iklGXe5o0c2ftFR754IgaUMCTIwGYao0Mpcg+0NuUHS+O4gw5F0SZnUp37sktwX4Xfv26bTbKPkV5TLO0h7mN8iv9TenfBu7bild2+PMHABEFZhlV0BXaiGWvQhpz/TOvIhUANrEP+3bNMRDRr337aUlELWBuotDrqswYVwk8LUiscf0jQD/Pc94xKUXcac=
