language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: heroku
  app: book-swap-meet
  api_key:
    secure: UATxtxudpdTkbuGp6gBwC8Ir4Z8QE4nbdpsydMOlU6amEobhvcnUf2qKPHbaH1+/kVnp3GQCUshCDWfUbdBKUn4C5tO3CzWjPIGOFaosF7AZF+lXqjCTU12ScmCn05xw2v5aPyhsxPGFKe2+o43ZmCEMZzGAXdAz/+Cu+xbyZRZwuPyur2tJWGnQzD9uQm2BZOTzEIH+GJQdEnydK4MJNrZXfGbDcNxySu+D3TsINYX6UkiANQv3IOGX8Fpg/CNuBIGrK/Q5FwdCT60StADZD1xDljNZ/MZeqvIuhHAfIWNirZ6tKY5IEjDEpDwZD0ejLrYkfWGkAd4b3rsk96nqj3McSpvfsV0JdFgAmslmEJo7t6kNcD4lEjO/7Gt8Twu1mYtK/sV0WbgI0LDPLU2Ervh9ADbvEyTzPi54JVcByYH7sfF5+8fnIbhzzpGFFIBgT4N4MbYwHqnyZPB9u1f3NWu1g1qrNnap6FkbLdgVasxFH2+PBxqvctJv4lnjdgFlOEY31FFp9PpkzA8DXpm4yjmMZz6P9MOuSvYDldgHRjOu3VpTKZ35O1Y2Er8Sxy7/SzAE5h6WYz6x2wmKiWxn1MWABsCYNuY4TcebE3uNISGkC9q64JUoGhDUy6fJ1f/JUA69v4me0S1tHAbzFwbuJIDqEXfXKr7nOOoIXQ8yHbc=
