export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

export const FETCH_USER_TRADES = 'FETCH_USER_TRADES';
export const FETCH_USER_TRADES_REJECTED = 'FETCH_USER_TRADES_REJECTED';
export const FETCH_USER_TRADES_FULFILLED = 'FETCH_USER_TRADES_FULFILLED';

export const FETCH_USER_BOOKS = 'FETCH_USER_BOOKS';
export const FETCH_USER_BOOKS_REJECTED = 'FETCH_USER_BOOKS_REJECTED';
export const FETCH_USER_BOOKS_FULFILLED = 'FETCH_USER_BOOKS_FULFILLED';

export const ADD_BOOK_TO_USER = 'ADD_BOOK_TO_USER';
export const ADD_BOOK_TO_USER_REJECTED = 'ADD_BOOK_TO_USER_REJECTED';
export const ADD_BOOK_TO_USER_FULFILLED = 'ADD_BOOK_TO_USER_FULFILLED';

export const REMOVE_BOOK_FROM_USER = 'REMOVE_BOOK_FROM_USER';
export const REMOVE_BOOK_FROM_USER_REJECTED = 'REMOVE_BOOK_FROM_USER_REJECTED';
export const REMOVE_BOOK_FROM_USER_FULFILLED = 'REMOVE_BOOK_FROM_USER_FULFILLED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';

export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const CITY_CHANGED = 'CITY_CHANGED';
export const STATE_CHANGED = 'STATE_CHANGED';

export const LOGIN = 'LOGIN';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
