export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

export const FETCH_USER_TRADES = 'FETCH_USER_TRADES';
export const FETCH_USER_TRADES_REJECTED = 'FETCH_USER_TRADES_REJECTED';
export const FETCH_USER_TRADES_FULFILLED = 'FETCH_USER_TRADES_FULFILLED';

export const FETCH_USER_BOOKS = 'FETCH_USER_BOOKS';
export const FETCH_USER_BOOKS_REJECTED = 'FETCH_USER_BOOKS_REJECTED';
export const FETCH_USER_BOOKS_FULFILLED = 'FETCH_USER_BOOKS_FULFILLED';

export const ADD_BOOK_TO_USER = 'ADD_BOOK_TO_USER';
export const ADD_BOOK_TO_USER_REJECTED = 'ADD_BOOK_TO_USER_REJECTED';
export const ADD_BOOK_TO_USER_FULFILLED = 'ADD_BOOK_TO_USER_FULFILLED';

export const REMOVE_BOOK_FROM_USER = 'REMOVE_BOOK_FROM_USER';
export const REMOVE_BOOK_FROM_USER_REJECTED = 'REMOVE_BOOK_FROM_USER_REJECTED';
export const REMOVE_BOOK_FROM_USER_FULFILLED = 'REMOVE_BOOK_FROM_USER_FULFILLED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';

export const EDIT_BTN_CLICK = 'EDIT_BTN_CLICK';
export const CANCEL_BTN_CLICK = 'CANCEL_BTN_CLICK';
export const SET_BOOK_TO_REMOVE = 'SET_BOOK_TO_REMOVE';
export const SEARCH_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE';

export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const PHONE_NUMBER_CHANGED = 'PHONE_NUMBER_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const CITY_CHANGED = 'CITY_CHANGED';
export const STATE_CHANGED = 'STATE_CHANGED';
export const EMAIL_NOTIFICATIONS_CLICKED = 'EMAIL_NOTIFICATIONS_CLICKED';
export const TEXT_NOTIFICATIONS_CLICKED = 'TEXTL_NOTIFICATIONS_CLICKED';

export const LOGIN = 'LOGIN';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGOUT = 'LOGOUT';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_REJECTED = 'SIGN_UP_REJECTED';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';

export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_ALL_BOOKS_REJECTED = 'FETCH_ALL_BOOKS_REJECTED';
export const FETCH_ALL_BOOKS_FULFILLED = 'FETCH_ALL_BOOKS_FULFILLED';

export const MAKE_TRADE_REQUEST = 'MAKE_TRADE_REQUEST';
export const MAKE_TRADE_REQUEST_REJECTED = 'MAKE_TRADE_REQUEST_REJECTED';
export const MAKE_TRADE_REQUEST_FULFILLED = 'MAKE_TRADE_REQUEST_FULFILLED';
export const VIEW_TRADE = 'VIEW_TRADE';

export const DECLINE_TRADE = 'DECLINE_TRADE';
export const DECLINE_TRADE_REJECTED = 'DECLINE_TRADE_REJECTED';
export const DECLINE_TRADE_FULFILLED = 'DECLINE_TRADE_FULFILLED';

export const ACCEPT_TRADE = 'ACCEPT_TRADE';
export const ACCEPT_TRADE_REJECTED = 'ACCEPT_TRADE_REJECTED';
export const ACCEPT_TRADE_FULFILLED = 'ACCEPT_TRADE_FULFILLED';

export const SET_REQUESTER_BOOK = 'SET_REQUESTER_BOOK';
export const SET_REQUESTEE_BOOK = 'SET_REQUESTEE_BOOK';
export const CANCEL_REQUESTER_BOOK = 'CANCEL_REQUESTER_BOOK';

export const SET_ERR_MSG = 'SET_ERR_MSG';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
